services:
  traefik:
    image: traefik:v3.3.1
    command:
      # Swarm provider configuration
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedByDefault=false"

      # EntryPoints for HTTP and HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Enable Let's Encrypt with ACME
      - "--certificatesResolvers.letsencrypt_resolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.letsencrypt_resolver.acme.storage=/letsencrypt/acme.json"
      # You can change this email if needed
      - "--certificatesResolvers.letsencrypt_resolver.acme.email=admin@${DOMAIN}"
      - "--certificatesResolvers.letsencrypt_resolver.acme.httpChallenge=true"

      # Enable dashboard (insecure for simplicity on vast, or protect if needed)
      - "--api.dashboard=true"
      - "--api.insecure=true" 
      - "--log.level=INFO"
      - "--ping=true"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    ports:
      - "80:80"
      - "443:443"
      # Expose dashboard on 8080
      - "8080:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=letsencrypt_resolver"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: unmute-frontend:latest
    build:
      context: frontend/
    deploy:
      replicas: 1
      update_config:
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.routers.frontend.tls.certresolver=letsencrypt_resolver"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.frontend.priority=10"

  backend:
    image: unmute-backend:latest
    build:
      context: ./
      target: prod
    environment:
      - KYUTAI_STT_URL=ws://tasks.stt:8080
      - KYUTAI_TTS_URL=ws://tasks.tts:8080
      - KYUTAI_LLM_URL=http://llm:8000
      - KYUTAI_VOICE_CLONING_URL=http://voice-cloning:8080
      - KYUTAI_REDIS_URL=redis://redis:6379
      - KYUTAI_VOICE_DONATION_DIR=/voice-donation
      - NEWSAPI_API_KEY=$NEWSAPI_API_KEY
      - KYUTAI_RECORDINGS_DIR=/recordings
      - KYUTAI_LLM_MODEL=$KYUTAI_LLM_MODEL
    volumes:
      - /scratch/voice-donation/:/voice-donation
      - recordings:/recordings
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=(Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend.middlewares=strip-api"
        - "traefik.http.middlewares.strip-api.replacepathregex.regex=^/api/(.*)"
        - "traefik.http.middlewares.strip-api.replacepathregex.replacement=/$$1"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt_resolver"
        - "traefik.http.services.backend.loadbalancer.server.port=80"
        - "traefik.http.routers.backend.priority=100"
      replicas: 1
      update_config:
        delay: 10s
      resources:
        limits:
          cpus: "2"
          memory: 4G

  tts:
    image: unmute-moshi-server:latest
    command: ["worker", "--config", "configs/tts-prod.toml"]
    build:
      context: services/moshi-server
      dockerfile: public.Dockerfile
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
      - HF_TOKEN=$HUGGING_FACE_HUB_TOKEN
    volumes:
      - cargo-registry:/root/.cargo/registry
      - moshi-server-target:/app/target
      - uv-cache:/root/.cache/uv
      - hf-cache:/root/.cache/huggingface/hub
      - tts-logs:/tmp/unmute_logs
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tts.rule=(Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)) && PathPrefix(`/tts-server`)"
        - "traefik.http.routers.tts.middlewares=strip-tts"
        - "traefik.http.middlewares.strip-tts.replacepathregex.regex=^/tts-server/(.*)"
        - "traefik.http.middlewares.strip-tts.replacepathregex.replacement=/$$1"
        - "traefik.http.routers.tts.entrypoints=websecure"
        - "traefik.http.routers.tts.tls=true"
        - "traefik.http.routers.tts.tls.certresolver=letsencrypt_resolver"
        - "traefik.http.services.tts.loadbalancer.server.port=8080"
        - "traefik.http.routers.tts.priority=100"
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 1

  stt:
    image: unmute-moshi-server:latest
    command: ["worker", "--config", "configs/stt-prod.toml"]
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
      - HF_TOKEN=$HUGGING_FACE_HUB_TOKEN
    volumes:
      - cargo-registry:/root/.cargo/registry
      - moshi-server-target:/app/target
      - uv-cache:/root/.cache/uv
      - hf-cache:/root/.cache/huggingface/hub
      - stt-logs:/tmp/unmute_logs
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.stt.rule=(Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)) && PathPrefix(`/stt-server`)"
        - "traefik.http.routers.stt.middlewares=strip-stt"
        - "traefik.http.middlewares.strip-stt.replacepathregex.regex=^/stt-server/(.*)"
        - "traefik.http.middlewares.strip-stt.replacepathregex.replacement=/$$1"
        - "traefik.http.routers.stt.entrypoints=websecure"
        - "traefik.http.routers.stt.tls=true"
        - "traefik.http.routers.stt.tls.certresolver=letsencrypt_resolver"
        - "traefik.http.services.stt.loadbalancer.server.port=8080"
        - "traefik.http.routers.stt.priority=100"
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 1

  voice-cloning:
    image: unmute-moshi-server:latest
    command: ["worker", "--config", "configs/voice-cloning.toml"]
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
      - HF_TOKEN=$HUGGING_FACE_HUB_TOKEN
    volumes:
      - cargo-registry:/root/.cargo/registry
      - moshi-server-target:/app/target
      - uv-cache:/root/.cache/uv
      - hf-cache:/root/.cache/huggingface/hub
      - voice-cloning-logs:/tmp/unmute_logs
    deploy:
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 1

  llm:
    image: vllm/vllm-openai:v0.11.0
    command:
      [
        "--model=${KYUTAI_LLM_MODEL}",
        "--max-model-len=8192",
        "--dtype=bfloat16",
        # "--tensor-parallel-size=1", # Assumes 1 GPU for LLM, verify if more needed
        "--tokenizer_mode=mistral",
        "--config_format=mistral",
        "--load-format=mistral",
      ]
    healthcheck:
      start_period: 10m
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    volumes:
      - "huggingface-cache:/root/.cache/huggingface"
      - vllm-cache:/root/.cache/vllm
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.llm.rule=(Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)) && PathPrefix(`/llm-server`)"
        - "traefik.http.routers.llm.middlewares=strip-llm"
        - "traefik.http.middlewares.strip-llm.replacepathregex.regex=^/llm-server/(.*)"
        - "traefik.http.middlewares.strip-llm.replacepathregex.replacement=/$$1"
        - "traefik.http.routers.llm.entrypoints=websecure"
        - "traefik.http.routers.llm.tls=true"
        - "traefik.http.routers.llm.tls.certresolver=letsencrypt_resolver"
        - "traefik.http.services.llm.loadbalancer.server.port=8000"
        - "traefik.http.routers.llm.priority=100"
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 1

  redis:
    image: redis:latest

networks:
  default:
    driver: overlay
    attachable: true

volumes:
  cargo-registry:
  moshi-server-target:
  uv-cache:
  hf-cache:
  voice-cloning-logs:
  letsencrypt:
  huggingface-cache:
  tts-logs:
  stt-logs:
  vllm-cache:
  recordings:
